version: "3"

services:
  backend:
    image: backend-img
    container_name: backend
    build:
      context: .
      dockerfile: backend.dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8091:1080"

  celery-worker:
    image: celery-img
    container_name: celery
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    build:
      context: .
      dockerfile: celeryworker.dockerfile


# volumes:
#   data:
